### ISSUE TITLE
Executing Slither on each AST separately will fail 

### ISSUE THREAD

**Issue by montyly** [embark-framework/embark-slither#1]
Thanks for creating this pugin!

Currently, the plugin will analyze the json of each `.sol` separately:  
https://github.com/embark-framework/embark-slither/blob/f008d9f306671d1fae309940a48772595bcda2f5/index.js#L25-L31

This leads to the following issues:
- Slither needs to have access to all the code, so the execution will fail if there is a file imported
- Even if we fix the import, Slither is meant to analyze the entire codebase at once. Several detectors are based on heuristics that will lead to FP if the entire scope is unknow. For example, Slither will detect unused variables. If `B` inherits from `A`, which declares a variable `my_var` only used in `B`,  Slither will incorrectly report that `A.my_var` is unused, while if it has access to `B` it will not.

I see two solutions:
- Create a temporary directoy, copy all the json files to this directory, and run `slither temporary_directory`
- Add the ability to specifiy a list of files to analyze to Slither

**Comment by alaibe** [comment]
We are already in a position where all contracts have been copied to a specific folder, so it should just be a matter of 
```
Create a temporary directoy, copy all the json files to this directory, and run slither temporary_directory
```

I will experiment with that, thanks for the hint

**Comment by montyly** [comment]
So I just tried, copying the separate AST to a directory won't work, because Slither assumes that a json file contains all the contracts, and will run each json file separately (`solc --ast-compact-json` creates one large json with all the contracts)

I am trying to find how to solve this

**Comment by alaibe** [comment]
It seems that the big json file is just a concat of all small one.
That might be easer for me and it would reduce the number of IO

Do you see anything bad in doing it that way?

**Comment by montyly** [comment]
No that's a good idea and it should work!

It's exactly what the solc output does

**Comment by alaibe** [comment]
Great, I will try to do it that way then
